# for train
DATA_TYPE = 'cifar10'
NUM_LOCAL_EPOCES = 10
NUM_TOTAL_EPOCHS = 10
NUM_CLIENTS = 20
LOCAL_ADAPTATION_EPOCHS = 1
INPUT_DIM = 28
LEARNING_RATE = 0.001
ALPHA = 0.0001
BETA = 0.0001
DELTA = 0.0001
SAMPLING_RATE = 0.5
BATCH_SIZE = 128
ALGORITHM = "Per-fl"
clients = [DATA_TYPE + '_' + str(i) + '.pickle' for i in range(NUM_CLIENTS)]
